server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth-service-db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: aquickbrownfoxjumpsoverthelazydogaquickbrownfoxjumpsoverthelazydog

logging:
  level:
    org.springframework.security: trace